services:
    markdown-to-html-converter-rest-api:
        image: fluxfw/flux-markdown-to-html-converter-rest-api:latest
        ports:
            - [%host_ip%:]9501:9501
        restart: always
    other-service:
        depends_on:
            - markdown-to-html-converter-rest-api
        environment:
            [- FLUX_MARKDOWN_TO_HTML_CONVERTER_REST_API_HOST=markdown-to-html-converter-rest-api]
            [- FLUX_MARKDOWN_TO_HTML_CONVERTER_REST_API_PORT=9501]
